### PR TITLE
Adding validations in sort by

### PR DESCRIPTION
**Pull request by MrPunyapal**
checking if it works if sorted by an in-valid column

### CODE REVIEW

**Comment by MrPunyapal** [comment]
@ludoguenet any suggestions?

**Comment by ludoguenet** [comment]
> @ludoguenet any suggestions?

Humm, I would use a when() instead of in_array ?

**Comment by MrPunyapal** [comment]
> > @ludoguenet any suggestions?
> 
> Humm, I would use a when() instead of in_array ?

example?

**Comment by ludoguenet** [comment]
> > > @ludoguenet any suggestions?
> > 
> > 
> > Humm, I would use a when() instead of in_array ?
> 
> example?

Sure, how can I properly show you a refactored version? :D

**Comment by MrPunyapal** [comment]
This is markdown...

```php

->when(condition,fn($q)=>$q->a(),fn($q)=>$q->b())

```


Or can I merge this pr and you can make a separate one?🤔

**Pull request merged**
