### PR TITLE
Add language translations for posts pages

### PR DESCRIPTION
**Pull request by MrPunyapal**
let's add translations

### CODE REVIEW

**Comment by MrPunyapal** [comment]
@dcblogdev @hosmelq @imrjat @ludoguenet 

what you think?

any opinions?

**Comment by dcblogdev** [comment]
looks good I tend to use the `__('JSON language version')`

where you write in the primary language then have translations for other languages.

**Comment by MrPunyapal** [comment]
> looks good I tend to use the `__('JSON language version')`
> 
> where you write in the primary language then have translations for other languages.

do we need to move to en.json?

**Comment by dcblogdev** [comment]
No, since you've already got the language files in place

**Comment by MrPunyapal** [comment]
Do you have any improvement ideas? 🤔
or additions?

**Comment by MrPunyapal** [comment]
Let's merge it for now 
Further developments will take place in new PR 🙌

**Pull request merged**
