### PR TITLE
Add FeaturedStatus enum to Post model

### PR DESCRIPTION
**Pull request by imrjat**
This enhancement helps improve code readability and maintainability, making it easier for developers to work with and understand the featured status logic within the Post model.

### CODE REVIEW

**Comment by MrPunyapal** [comment]
this can help 🫡

```bash
./vendor/bin/pint --dirty
```

**Comment by imrjat** [comment]
Screenshot from 2023-12-11 19-09-32

**Comment by MrPunyapal** [comment]
try this
```bash
./vendor/bin/pint --test
```

**Comment by imrjat** [comment]
Same
Screenshot from 2023-12-11 19-13-49

**Comment by MrPunyapal** [comment]
> try this
> 
> ```shell
> ./vendor/bin/pint --test
> ```

you took the pull right? 🤔

**Pull request merged**
