### PR TITLE
Refactor Settings class

### PR DESCRIPTION
**Pull request by imrjat**
1. Change class to final for prevention of inheritance
2. Replace hardcoded arrays with constants for categories and tags

### CODE REVIEW

**Comment by MrPunyapal** [comment]
@dcblogdev what you think?

**Comment by dcblogdev** [comment]
in my opinion `final` is not needed, especially on an early project.

I think sticking with array over constant that way in userland the arrays can be added to if needs be.

**Comment by imrjat** [comment]
> in my opinion `final` is not needed, especially on an early project.
> 
> I think sticking with array over constant that way in userland the arrays can be added to if needs be.


@dcblogdev  Thanks for sharing your opinion! I appreciate the feedback. I added the `final` keyword to prevent unintentional inheritance as it is a simple utility class with static data. However, I understand your point about flexibility in userland. If the project evolves in a way that requires dynamic changes to the arrays, we can certainly revisit this decision. Let's keep an eye on the project's needs and adapt accordingly.

**Comment by MrPunyapal** [comment]
actually I'm thinking to move categories into categories table in database (to give example of working with related data)

and maybe we can merge it now and change things later?

**Comment by imrjat** [comment]
@dcblogdev @mr-punyapal Appreciate the thoughtful discussion! I see merit in both perspectives and agree with both of you.

**Pull request merged**
