### PR TITLE
added tests for posts

### PR DESCRIPTION
**Pull request by dcblogdev**
Added Pest tests for post and unit test for settings
Added return types
Changed `redirect()->route` to `to_route`
Changed category to be an array instead of an int

### CODE REVIEW

**Comment by MrPunyapal** [comment]
Any reasons to make a category array 🤔

**Comment by dcblogdev** [comment]
ah I didn't look at the views, but is an int the right call there since the categories are array keys in the settings class, maybe a string would make more sense?

**Comment by dcblogdev** [comment]
I'll revert this part.

**Comment by MrPunyapal** [comment]
Let's rename it to category_id 🤔

I have plans to bring them from the database in the future

**Comment by dcblogdev** [comment]
do you want that part of this PR?

**Comment by MrPunyapal** [comment]
Okay done I'm merging it

**Pull request merged**
